CREATE DATABASE WEB
GO

USE WEB
GO

CREATE TABLE QUYEN
(
	IdQuyen VARCHAR(100),
	TenQuyen NVARCHAR(50),
	CONSTRAINT PK_QUYEN PRIMARY KEY(IdQuyen)
)
GO


CREATE TABLE CHUCVU
(
	IdCVu INT IDENTITY(1,1),
	TenCVu NVARCHAR(50),
	CONSTRAINT PK_CVU PRIMARY KEY(IdCVu)
)
GO

CREATE TABLE USERTYPE
(
	IdUT INT IDENTITY(1,1),
	TenUT NVARCHAR(100),
	CONSTRAINT PK_UT PRIMARY KEY(IdUT)
)

CREATE TABLE USERTYPE_QUYEN
(
	IdUT INT,
	Quyen VARCHAR(100),
	GhiChu NVARCHAR(500),
	CONSTRAINT PK_UTQ PRIMARY KEY(IdUT,Quyen),
	CONSTRAINT FK_UTQ_UT FOREIGN KEY(IdUT) REFERENCES dbo.USERTYPE(IdUT),
	CONSTRAINT FK_UTQ_QUYEN FOREIGN KEY(Quyen) REFERENCES dbo.QUYEN(IdQuyen)
)
GO


CREATE TABLE CHUYENNGANH
(
	IdCNganh INT IDENTITY(1,1),
	TenCNganh NVARCHAR(50),
	CONSTRAINT PK_CNGANH PRIMARY KEY(IdCNganh)
)
GO

CREATE TABLE NIENKHOA
(
	IdNK INT IDENTITY(1,1),
	TenNK NVARCHAR(50),
	NamBD INT,
	NamKT INT
	CONSTRAINT PK_NKHOA PRIMARY KEY(IdNK)
)
GO


CREATE TABLE LOP
(
	IdLop INT IDENTITY(1,1),
	TenLop NVARCHAR(50),
	IdNK INT
	CONSTRAINT PK_LOP PRIMARY KEY(IdLop)
	CONSTRAINT FK_LOP_NKHOA FOREIGN KEY(IdNK) REFERENCES dbo.NIENKHOA(IdNK)
)
GO


CREATE TABLE NGUOIDUNG
(
	IdUser INT IDENTITY(1,1),
	Name NVARCHAR(50),
	Username VARCHAR(50),
	Email VARCHAR(50),
	Avatar VARCHAR(500),
	Block BIT,
	RegisterDate DATE,
	LastVisitDate DATE,
	Phone VARCHAR(15),
	HocVi NVARCHAR(50),
	ChuyenNganh INT,
	Lop INT,
	ChucVu INT,
	Diem FLOAT,
	TongTC INT,
	Password VARCHAR(50)
	CONSTRAINT PK_USER PRIMARY KEY(IdUser),
	CONSTRAINT FK_USER_CVU FOREIGN KEY(ChucVu) REFERENCES dbo.CHUCVU(IdCVu),
	CONSTRAINT FK_USER_CNGANH FOREIGN KEY(ChuyenNganh) REFERENCES dbo.CHUYENNGANH(IdCNganh),
	CONSTRAINT FK_USER_LOP FOREIGN KEY(Lop) REFERENCES dbo.LOP(IdLop),
)
GO
 ALTER TABLE dbo.NGUOIDUNG ADD NgaySinh DATE
 GO

 ALTER TABLE dbo.NGUOIDUNG ADD GioiTinh BIT NOT NULL DEFAULT(1)
 GO

ALTER TABLE dbo.NGUOIDUNG ADD CONSTRAINT U_USER UNIQUE(Username)

ALTER TABLE dbo.NGUOIDUNG ADD IdUT INT

ALTER TABLE dbo.NGUOIDUNG ADD CONSTRAINT FK_USER_UT FOREIGN KEY(IdUT) REFERENCES dbo.USERTYPE(IdUT)


CREATE TABLE LOAIDETAI
(
	IdLoai INT IDENTITY(1,1),
	TenLoai NVARCHAR(50),
	CONSTRAINT PK_LOAIDT PRIMARY KEY(IdLoai)
)
GO


--Cho them thuoc tinh nguoi tao ra cau hinh, va bo di bang sinh vien cau hinh
CREATE TABLE CAUHINH
(
	IdCauHinh INT IDENTITY(1,1),
	SoLuongSVToiDa INT,
	Active BIT,
	ThoiGianBatDauDK DATETIME,
	ThoiGianKetThucDK DATETIME,
	LoaiDT INT,
	NienKhoa INT,
	HocKy INT,
	NamHocBatDauHocKy INT,
	NamHocKetThucHocKy INT,
	ThoiGianGVBatDauDK DATETIME,
	ThoiGianGVKetThucDK DATETIME,
	ThoiGianSVBatDauNopBC DATETIME,
	ThoiGianSVKetThucNopBC DATETIME,
	DateUpdate DATETIME,
	ThoiGianBatDauDuyet DATETIME,
	ThoiGianKetThucDuyet DATETIME,
	NguoiTao INT,
	CONSTRAINT PK_CAUHINH PRIMARY KEY(IdCauHinh),
	CONSTRAINT FK_CAUHINH_LOAIDT FOREIGN KEY(LoaiDT) REFERENCES dbo.LOAIDETAI(IdLoai),
	CONSTRAINT FK_CAUHINH_NKHOA FOREIGN KEY(NienKhoa) REFERENCES dbo.NIENKHOA(IdNK),
	CONSTRAINT FK_CAUHINH_NGUOITAO FOREIGN KEY(NguoiTao) REFERENCES dbo.NGUOIDUNG(IdUser)
)
GO

ALTER TABLE dbo.CAUHINH ADD folderDriveID  VARCHAR(300)
GO


CREATE TABLE TRANGTHAI
(
	IdTT INT IDENTITY(1,1),
	TenTT NVARCHAR(20),
	CONSTRAINT PK_TRANGTHAI PRIMARY KEY(IdTT)
)
GO


CREATE TABLE DETAI
(
	IdDeTai INT IDENTITY(1,1),
	TenDeTai NVARCHAR(2000),
	MucTieu NVARCHAR(MAX),
	YeuCau NVARCHAR(MAX),
	SanPham NVARCHAR(2000),
	ChuThich NVARCHAR(2000),
	ThoiGianBDBaoVe DATETIME,
	ThoiGianKTBaoVe DATETIME,
	ChuyenNganh INT,
	TrangThai INT,
	TruongNhom INT,
	CauHinh INT,
	IsDelete BIT,
	DuocDKKhacCN BIT,
	File_source VARCHAR(500),
	File_word VARCHAR(500),
	File_powerpoint VARCHAR(500),
	GVHuongDan INT,
	PhongBaoVe VARCHAR(20),
	IsDuyet BIT,
	SoLuongSV INT,
	CONSTRAINT PK_DETAI PRIMARY KEY(IdDeTai),
	CONSTRAINT FK_DETAI_CAUHINH FOREIGN KEY(CauHinh) REFERENCES dbo.CAUHINH(IdCauHinh),
	CONSTRAINT FK_DETAI_CNGANH FOREIGN KEY(ChuyenNganh) REFERENCES dbo.CHUYENNGANH(IdCNganh),
	CONSTRAINT FK_DETAI_TRANGTHAI FOREIGN KEY(TrangThai) REFERENCES dbo.TRANGTHAI(IdTT),
	CONSTRAINT FK_DETAI_TRUONGNHOM FOREIGN KEY(TruongNhom) REFERENCES dbo.NGUOIDUNG(IdUser),
	CONSTRAINT FK_DETAI_GVHD FOREIGN KEY(GVHuongDan) REFERENCES dbo.NGUOIDUNG(IdUser),
)
GO


CREATE TABLE SINHVIEN_DETAI
(
	DeTai INT,
	SinhVien INT,
	Diem FLOAT(2),
	CONSTRAINT PK_SVDT PRIMARY KEY(DeTai,SinhVien),
	CONSTRAINT FK_SVDT_SINHVIEN FOREIGN KEY(SinhVien) REFERENCES dbo.NGUOIDUNG(IdUser),
	CONSTRAINT FK_SVDT_DETAI FOREIGN KEY(DeTai) REFERENCES dbo.DETAI(IdDeTai)
)
GO



CREATE TABLE XINVAONHOM
(
	NguoiGui INT,
	DeTai INT,
	ThoiGian DATETIME,
	CONSTRAINT PK_XINVN PRIMARY KEY(NguoiGui,DeTai),
	CONSTRAINT FK_XINVN_SV FOREIGN KEY(NguoiGui) REFERENCES dbo.NGUOIDUNG(IdUser),
	CONSTRAINT FK_XINVN_DT FOREIGN KEY(DeTai) REFERENCES dbo.DETAI(IdDeTai)
)
GO

CREATE TABLE THONGBAO
(
	IdTB INT IDENTITY(1,1),
	TenTB NVARCHAR(200),
	NoiDung NVARCHAR(1000),
	NguoiDang INT,
	NgayDang DATETIME,
	SoNgayHienThi INT,
	CoTinMoi BIT, -- co la tin moi hay khong
	IsDelete BIT,--xoa hay khong
	CONSTRAINT PK_THONGBAO PRIMARY KEY(IdTB),
	CONSTRAINT FK_TB_NGUOIDANG FOREIGN KEY(NguoiDang) REFERENCES dbo.NGUOIDUNG(IdUser)
)
GO
ALTER TABLE dbo.THONGBAO DROP COLUMN NoiDung
GO

ALTER TABLE dbo.THONGBAO ADD NoiDung NTEXT

GO

CREATE VIEW v_ThongBao
AS 
SELECT IdTB,TenTB,NguoiDang,NgayDang,SoNgayHienThi,CoTinMoi,NoiDung FROM dbo.THONGBAO
WHERE IsDelete=0